name: Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: "Production"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: yarn

      - name: Install Node Dependencies
        run: yarn install --immutable

      - name: Pull Vercel Environment Information
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Run Database Migrations
        run: yarn db:check && yarn db:migrate

      - name: Deploy Project
        run: yarn vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
